// Generated by Wrangler on Wed Oct 16 2024 11:08:11 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	SHORT_URLS: KVNamespace;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
}
